cdp: improved routing and removed useless warning/errors in authstatemachine
kamailio/kamailio pull request #3914
Opened 2024-07-12 12:07 UTC by vingarzan

#### Pre-Submission Checklist

- [x] Commit message has the format required by CONTRIBUTING guide
- [x] Commits are split per component (core, individual modules, libs, utils, ...)
- [x] Each component has a single commit (if not, squash them into one commit)
- [x] No commits to README files for modules (changes must be done to docbook files
in `doc/` subfolder, the README file is autogenerated)

#### Type Of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:

- [ ] PR should be backported to stable branches
- [x] Tested changes locally
- [ ] Related to issue #XXXX (replace XXXX with an open issue number)

#### Description

Diameter requests could contain Application-Ids in multiple AVPs. This fix iterates through them, instead of giving up if the first one does not match. This solves some issues when peers don't always declare support for vendor-specific/non-specific application ids, so routing should be easier.

Also fixed:
- auth state machine being too verbose on regular messages being received or sent while in the Open state
- add Destination-Host from auth state to requests (next-hop immediate routing)

2024-07-13 16:37 UTC, herlesupreeth requested changes

2024-07-13 16:37 UTC, herlesupreeth commented on src/modules/cdp/authstatemachine.c
> +					//LM_INFO("state machine: I was in open and I am going to open\n");
I thin we can remove this commented code

2024-07-13 16:37 UTC, herlesupreeth commented on src/modules/cdp/authstatemachine.c
> +					//LM_INFO("state machine: I was in open and I am going to discon\n");
same as above. remove the commented code

2024-07-13 16:37 UTC, herlesupreeth commented on src/modules/cdp/authstatemachine.c
> +					//LM_INFO("state machine: I was in open and I am going to discon\n");
same as above

2024-07-13 16:37 UTC, herlesupreeth commented on src/modules/cdp/authstatemachine.c
> +					//LM_INFO("state machine: I was in open and I am going to discon\n");
same as above

2024-07-13 16:37 UTC, herlesupreeth commented on src/modules/cdp/authstatemachine.c
> +					//LM_INFO("state machine: I was in open and I am going to open\n");
remove commented code

2024-07-13 16:52 UTC, herlesupreeth commented on src/modules/cdp/routing.c
> +	if(!config->r_table) {
cant we remove this check here as its already done in `get_peer_by_fqdn` ??

2024-07-13 16:52 UTC, herlesupreeth commented on src/modules/cdp/routing.c
> +	if(destination_host.len) {
cant we remove this check here as its already done in `get_peer_by_fqdn` ??

2024-07-13 16:54 UTC, herlesupreeth commented
Thanks @vingarzan. Looks good to me.

2024-07-14 09:26 UTC, vingarzan commented
> Thanks @vingarzan. Looks good to me.

Thank you also for the review! I have removed the commented out logs.

2024-07-14 09:27 UTC, herlesupreeth approved these changes

2024-07-14 09:46 UTC, merged